cc = gcc -Wall
FILES = obj/main.o #liste des fichiers sources avec .o

#options suivant le système uttilisé
ifeq ($(OS), Windows_NT)
	OPT = -lm -lmingw32 -lSDL2main -lSDL2 #-lSDL2_ttf -lSDL2_image
else
	OPT = `pkg-config --libs --cflags sdl2`
endif


all: 2048 #commande pour compiler et lancer le jeu
	./2048

2048: $(FILES) #commande pour compiler le jeu
	clean
	$(cc) $^ -o $@ $(OPT)

obj/%o: src/%c #commande de création des .o avec les .c
	$(cc) -c $^ -o $@ $(OPT) 

clean: #commande pour retirer tous les fichiers objects
	ifeq ($(OS), Windows_NT)
		rm obj/*.o
	else
		sudo rm obj/*.obj
	endif